import '../styles/globals.css'
import type { Metadata } from 'next'
import Provider from '@/components/common/Provider'
import Header from '@/components/common/Header'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head />
      <Provider>
        <body>
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  )
}
